export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEDEX_SUCCESS = 'FETCH_POKEDEX_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const FETCH_MORE_POKEDEX_SUCCESS = 'FETCH_MORE_POKEDEX_SUCCESS';
export const REMOVE_EXTRA_POKEMON = 'REMOVE_EXTRA_POKEMON';
